# PENGENALAN TENSORFLOW

Alan Nuzulan
2009106032

In [18]:
#Import Tensor

import tensorflow as tf

In [19]:
#Membuat tensor dengan nilai random dan shape [5,5] serta nilai rata ratanya adalah 10

random_tensor = tf.Variable(tf.random.normal([5,5],mean=10))
print(random_tensor)

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[10.477187 ,  9.853338 , 10.372623 ,  9.681533 ,  7.3481894],
       [ 9.123603 , 11.110659 ,  8.618059 , 11.183033 , 11.970716 ],
       [10.295937 ,  8.934179 ,  9.682997 ,  9.371412 ,  9.815532 ],
       [ 9.362932 , 10.718375 , 10.179168 ,  9.315796 ,  9.800442 ],
       [10.189053 , 11.337361 , 10.239808 ,  8.87012  ,  9.929071 ]],
      dtype=float32)>


In [20]:
#Membuat list bilangan prima, lalu menjadikannya tensor [5,5] dengan type float32

prima = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,101]
prime_tensor = tf.Variable(tf.convert_to_tensor(prima,dtype=tf.float32))
prime_tensor = tf.reshape(prime_tensor,[5,5])
print(prime_tensor)

tf.Tensor(
[[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  67.  71.]
 [ 73.  79.  83.  89. 101.]], shape=(5, 5), dtype=float32)


In [21]:
#Menampilkan dimensi dari random_tensor

print(random_tensor.get_shape())

(5, 5)


In [22]:
#Menampilkan dimensi dari prime_tensor

print(prime_tensor.get_shape())

(5, 5)


In [23]:
#Menambahkan 2 tensor yang sudah di buat

print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 12.477187  12.853338  15.372623  16.681534  18.34819 ]
 [ 22.123604  28.110659  27.61806   34.183033  40.97072 ]
 [ 41.295937  45.93418   50.683     52.371414  56.815533]
 [ 62.36293   69.718376  71.17917   76.315796  80.800446]
 [ 83.18906   90.337364  93.23981   97.87012  110.92907 ]], shape=(5, 5), dtype=float32)


In [24]:
#Mengurangi random_tensor dengan prime_tensor yang sudah di buat

print(tf.math.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[  8.477187    6.8533382   5.3726234   2.6815329  -3.6518106]
 [ -3.8763971  -5.8893414 -10.381941  -11.816967  -17.029284 ]
 [-20.704063  -28.06582   -31.317003  -33.628586  -37.184467 ]
 [-43.63707   -48.281624  -50.82083   -57.684204  -61.19956  ]
 [-62.810947  -67.662636  -72.76019   -80.12988   -91.07093  ]], shape=(5, 5), dtype=float32)


In [25]:
#Mengalikan 2 tensor yang sudah di buat

print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  20.954374   29.560015   51.863117   67.77073    80.830086]
 [ 118.606834  188.8812    163.74312   257.20975   347.1508  ]
 [ 319.17404   330.56464   397.00287   402.97073   461.33    ]
 [ 496.2354    632.38416   620.92926   624.1583    695.83136 ]
 [ 743.80084   895.65155   849.90405   789.4407   1002.83624 ]], shape=(5, 5), dtype=float32)


In [26]:
#Membagi random_tensor dengan prime_tensor yang sudah di buat

print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[5.2385936  3.284446   2.0745246  1.3830761  0.6680172 ]
 [0.7018156  0.65356815 0.45358205 0.48621884 0.41278332]
 [0.33212698 0.2414643  0.23617065 0.21793982 0.2088411 ]
 [0.17665909 0.18166737 0.1668716  0.13904174 0.13803439]
 [0.13957606 0.14351091 0.12337118 0.09966427 0.09830764]], shape=(5, 5), dtype=float32)


In [27]:
#Melakukan Matrik Multiplication random_tensor dengan prime_tensor yang sudah di buat

print(tf.matmul(random_tensor, prime_tensor))

tf.Tensor(
[[1520.1382 1734.4427 1865.3501 2048.6414 2318.0652]
 [1896.4087 2140.6057 2285.7954 2504.6438 2830.6553]
 [1650.1278 1869.3801 2004.5773 2195.3936 2484.1863]
 [1682.7883 1910.7972 2049.51   2246.165  2543.5122]
 [1680.1365 1909.9088 2051.3777 2250.38   2554.7488]], shape=(5, 5), dtype=float32)


In [28]:
#Mencari Nilai Maksimal dari random_tensor

print(tf.reduce_max(random_tensor))

tf.Tensor(11.970716, shape=(), dtype=float32)


In [29]:
#Mencari Nilai Minimal dari random_tensor

print(tf.reduce_min(random_tensor))

tf.Tensor(7.3481894, shape=(), dtype=float32)


In [30]:
#Menggabungkan dua tensor

Concatenation = tf.concat([random_tensor,prime_tensor],axis=0)
print(Concatenation)

tf.Tensor(
[[ 10.477187    9.853338   10.372623    9.681533    7.3481894]
 [  9.123603   11.110659    8.618059   11.183033   11.970716 ]
 [ 10.295937    8.934179    9.682997    9.371412    9.815532 ]
 [  9.362932   10.718375   10.179168    9.315796    9.800442 ]
 [ 10.189053   11.337361   10.239808    8.87012     9.929071 ]
 [  2.          3.          5.          7.         11.       ]
 [ 13.         17.         19.         23.         29.       ]
 [ 31.         37.         41.         43.         47.       ]
 [ 53.         59.         61.         67.         71.       ]
 [ 73.         79.         83.         89.        101.       ]], shape=(10, 5), dtype=float32)


In [31]:
#Mengurutkan random_tensor dari yang terbesar

random_tensorV2 = tf.reshape(random_tensor,[25])
Sort1 = tf.sort(random_tensorV2,direction="DESCENDING")
print(Sort1)

tf.Tensor(
[11.970716  11.337361  11.183033  11.110659  10.718375  10.477187
 10.372623  10.295937  10.239808  10.189053  10.179168   9.929071
  9.853338   9.815532   9.800442   9.682997   9.681533   9.371412
  9.362932   9.315796   9.123603   8.934179   8.87012    8.618059
  7.3481894], shape=(25,), dtype=float32)


In [32]:
#Mengurutkan random_tensor dari yang terbesar

prime_tensorV2 = tf.reshape(prime_tensor,[25])
Sort2 = tf.sort(prime_tensorV2,direction="DESCENDING")
print(Sort2)

tf.Tensor(
[101.  89.  83.  79.  73.  71.  67.  61.  59.  53.  47.  43.  41.  37.
  31.  29.  23.  19.  17.  13.  11.   7.   5.   3.   2.], shape=(25,), dtype=float32)
