# PENGENALAN TENSORFLOW

Alan Nuzulan
2009106032

In [19]:
#Import Tensor

import tensorflow as tf

In [20]:
#Membuat tensor dengan nilai random dan shape [5,5] serta nilai rata ratanya adalah 10

random_tensor = tf.Variable(tf.random.normal([5,5],mean=10))
random_tensor

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[10.758855, 10.181848,  8.826671, 11.069616, 11.282988],
       [10.002104,  9.135122,  9.332851, 10.353046, 11.256962],
       [10.638362,  9.060931, 10.143249,  8.51138 ,  9.761782],
       [10.312356,  9.97228 ,  9.124411,  9.027073, 12.035595],
       [ 9.18998 , 10.736526,  9.12397 , 11.335119,  8.989352]],
      dtype=float32)>

In [21]:
#Membuat list bilangan prima, lalu menjadikannya tensor [5,5] dengan type float32

prima = [2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,101]
prime_tensor = tf.Variable(tf.convert_to_tensor(prima,dtype=tf.float32))
prime_tensor = tf.reshape(prime_tensor,[5,5])
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  67.,  71.],
       [ 73.,  79.,  83.,  89., 101.]], dtype=float32)>

In [22]:
#Menampilkan dimensi dari random_tensor

random_tensor.get_shape()

TensorShape([5, 5])

In [23]:
#Menampilkan dimensi dari prime_tensor

prime_tensor.get_shape()

TensorShape([5, 5])

In [24]:
#Menambahkan 2 tensor yang sudah di buat

print(tf.add(random_tensor, prime_tensor))

tf.Tensor(
[[ 12.758855  13.181848  13.826671  18.069616  22.282988]
 [ 23.002104  26.135122  28.332851  33.353046  40.25696 ]
 [ 41.638363  46.060932  51.14325   51.51138   56.76178 ]
 [ 63.312355  68.97228   70.12441   76.02707   83.0356  ]
 [ 82.18998   89.73653   92.12397  100.33512  109.98935 ]], shape=(5, 5), dtype=float32)


In [25]:
#Mengurangi random_tensor dengan prime_tensor yang sudah di buat

print(tf.math.subtract(random_tensor, prime_tensor))

tf.Tensor(
[[  8.758855    7.1818476   3.8266706   4.0696163   0.2829876]
 [ -2.9978962  -7.8648777  -9.667149  -12.646954  -17.743038 ]
 [-20.361637  -27.939068  -30.85675   -34.48862   -37.23822  ]
 [-42.687645  -49.02772   -51.875587  -57.972927  -58.964405 ]
 [-63.81002   -68.26347   -73.87603   -77.66488   -92.01065  ]], shape=(5, 5), dtype=float32)


In [26]:
#Mengalikan 2 tensor yang sudah di buat

print(tf.multiply(random_tensor, prime_tensor))

tf.Tensor(
[[  21.51771    30.545544   44.133354   77.48731   124.11286 ]
 [ 130.02734   155.29707   177.32417   238.12007   326.4519  ]
 [ 329.7892    335.25446   415.8732    365.98935   458.80374 ]
 [ 546.5549    588.3645    556.58905   604.8139    854.5272  ]
 [ 670.8685    848.18555   757.2895   1008.8256    907.92456 ]], shape=(5, 5), dtype=float32)


In [27]:
#Membagi random_tensor dengan prime_tensor yang sudah di buat

print(tf.divide(random_tensor, prime_tensor))

tf.Tensor(
[[5.3794274  3.3939493  1.7653341  1.5813738  1.0257262 ]
 [0.7693926  0.53736013 0.4912027  0.45013246 0.3881711 ]
 [0.34317297 0.24489003 0.2473963  0.19793907 0.20769748]
 [0.19457276 0.16902168 0.14958051 0.13473243 0.16951542]
 [0.12589014 0.13590539 0.10992735 0.1273609  0.08900349]], shape=(5, 5), dtype=float32)


In [28]:
#Melakukan Matrik Multiplication random_tensor dengan prime_tensor yang sudah di buat

print(tf.matmul(random_tensor, prime_tensor))

tf.Tensor(
[[1837.8562 2076.4182 2220.8774 2434.8914 2753.999 ]
 [1798.5488 2030.7485 2172.0884 2376.9587 2685.6052]
 [1617.2228 1834.6034 1970.6448 2158.0906 2446.7695]
 [1790.1544 2021.4783 2164.7417 2369.8804 2687.9966]
 [1697.7817 1926.6086 2061.5852 2263.106  2553.9937]], shape=(5, 5), dtype=float32)


In [29]:
#Mencari Nilai Maksimal dari random_tensor

tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=12.035595>

In [30]:
#Mencari Nilai Minimal dari random_tensor

tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=8.51138>

In [31]:
#Menggabungkan dua tensor

Concatenation = tf.concat([random_tensor,prime_tensor],axis=0)
Concatenation

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 10.758855,  10.181848,   8.826671,  11.069616,  11.282988],
       [ 10.002104,   9.135122,   9.332851,  10.353046,  11.256962],
       [ 10.638362,   9.060931,  10.143249,   8.51138 ,   9.761782],
       [ 10.312356,   9.97228 ,   9.124411,   9.027073,  12.035595],
       [  9.18998 ,  10.736526,   9.12397 ,  11.335119,   8.989352],
       [  2.      ,   3.      ,   5.      ,   7.      ,  11.      ],
       [ 13.      ,  17.      ,  19.      ,  23.      ,  29.      ],
       [ 31.      ,  37.      ,  41.      ,  43.      ,  47.      ],
       [ 53.      ,  59.      ,  61.      ,  67.      ,  71.      ],
       [ 73.      ,  79.      ,  83.      ,  89.      , 101.      ]],
      dtype=float32)>

In [32]:
#Mengurutkan random_tensor dari yang terbesar

random_tensorV2 = tf.reshape(random_tensor,[25])
Sort1 = tf.sort(random_tensorV2,direction="DESCENDING")
Sort1

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([12.035595, 11.335119, 11.282988, 11.256962, 11.069616, 10.758855,
       10.736526, 10.638362, 10.353046, 10.312356, 10.181848, 10.143249,
       10.002104,  9.97228 ,  9.761782,  9.332851,  9.18998 ,  9.135122,
        9.124411,  9.12397 ,  9.060931,  9.027073,  8.989352,  8.826671,
        8.51138 ], dtype=float32)>

In [33]:
#Mengurutkan random_tensor dari yang terbesar

prime_tensorV2 = tf.reshape(prime_tensor,[25])
Sort2 = tf.sort(prime_tensorV2,direction="DESCENDING")
Sort2

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([101.,  89.,  83.,  79.,  73.,  71.,  67.,  61.,  59.,  53.,  47.,
        43.,  41.,  37.,  31.,  29.,  23.,  19.,  17.,  13.,  11.,   7.,
         5.,   3.,   2.], dtype=float32)>